/** @format */
'use client'
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
  header: string;
}) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body
          className={
            process.env.NODE_ENV === "development" ? "debug-screens" : ""
          }
        >
          {children}
        </body>
      </html>
    </QueryClientProvider>
  );
}
